### ISSUE TITLE
No module named 'ray_casting_mlc.models.LGTNet'

### ISSUE THREAD

**Issue by Laplace-Y** [EnriqueSolarte/ray_casting_mlc#2]
Hi,

I encountered an issue when running the following command:
python experiments/lgt_net/create_pseudo_labels/pre_compute_mlc.py dataset=hm3d_mvl

The error message is:

```bash
Traceback (most recent call last):
  File "/home/laplace/ray_casting_mlc/experiments/lgt_net/create_pseudo_labels/pre_compute_mlc.py", line 13, in <module>
    from ray_casting_mlc.models.wrapper_lgt_net import wrapper_lgt_net as lg
  File "/home/laplace/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/ray_casting_mlc/models/wrapper_lgt_net/__init__.py", line 2, in <module>
    import ray_casting_mlc.models.wrapper_lgt_net.wrapper_lgt_net as lgt_net
  File "/home/laplace/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/ray_casting_mlc/models/wrapper_lgt_net/wrapper_lgt_net.py", line 9, in <module>
    from ray_casting_mlc.models.LGTNet.models.lgt_net import LGT_Net
ModuleNotFoundError: No module named 'ray_casting_mlc.models.LGTNet'
It seems that Python cannot find the module ray_casting_mlc.models.LGTNet.
```

I’ve checked the directory structure, but  the folder LGTNet seems to be completely empty. Could you let me know if there are any additional steps to set up the project or if I missed something?

Thank you for your help!

**Comment by EnriqueSolarte** [comment]
Hi,

Yes, I can see where the bug is. In our implementation, we add two layout models as git submodules. These models are taken directly from a forked version of the original models (LGTNet and HorizonNet). These submodules seem missing, so the directories `ray_casting_mlc/models/HorizonNet` and `ray_casting_mlc/model/LGTNet` are empty. 

For your particular case, you can run the following commands:
```bash
cd ray_casting_mlc
git submodule update --init --recursive
```
More information on why the submodules were not cloned can be found here https://stackoverflow.com/questions/3796927/how-do-i-git-clone-a-repo-including-its-submodules

Please, let me know if this solves your issue.

**Comment by Laplace-Y** [comment]
Hi,

First of all, thank you for answering my previous question.

I encountered an issue when running the command:
```
python experiments/lgt_net/create_pseudo_labels/pre_compute_mlc.py dataset=hm3d_mvl
```
The error message is:
```
Traceback (most recent call last):
  File "/home/laplace/ray_casting_mlc_ws/ray_casting_mlc/experiments/lgt_net/create_pseudo_labels/pre_compute_mlc.py", line 13, in <module>
    from ray_casting_mlc.models.wrapper_lgt_net import wrapper_lgt_net as lg
  File "/home/laplace/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/ray_casting_mlc/models/wrapper_lgt_net/__init__.py", line 2, in <module>
    import ray_casting_mlc.models.wrapper_lgt_net.wrapper_lgt_net as lgt_net
  File "/home/laplace/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/ray_casting_mlc/models/wrapper_lgt_net/wrapper_lgt_net.py", line 9, in <module>
    from ray_casting_mlc.models.LGTNet.models.lgt_net import LGT_Net
ModuleNotFoundError: No module named 'ray_casting_mlc.models.LGTNet'
```
I noticed that the script you provided in the README (python experiments/lgt_net/pre_compute_mlc.py dataset=hm3d_mvl) is located in experiments/lgt_net/create_pseudo_labels/pre_compute_mlc.py in the project. After adjusting the path, the same error still occurs.

Additionally, I am unsure if my downloaded dataset is complete and properly set up. Could you please provide an example or detailed instructions on how to correctly use the dataset ? This would greatly help me understand the correct setup and workflow.

Thank you again for your assistance!

**Comment by EnriqueSolarte** [comment]
Hi, 

I saw your open issue [HERE](https://github.com/EnriqueSolarte/multiview-datasets/issues/1) in the Multi-view Dataset REPO. I answered [HERE](https://github.com/EnriqueSolarte/multiview-datasets/issues/1#issuecomment-2496064917). 
The dataset must have the following structure. 

```bash 
.
├── hm3d_mvl
│   ├── geometry_info
│   ├── img
│   ├── labels
│   ├── scene_list__testing_set.json
│   └── scene_list__training_set.json
├── mp3d_fpe_mvl
│   ├── geometry_info
│   ├── img
│   ├── labels
│   ├── scene_list__testing_set.json
│   └── scene_list__training_set.json
└── zind_mvl
    ├── geometry_info
    ├── img
    ├── labels
    ├── scene_list__testing_set.json
    └── scene_list__training_set.json
```
Let me know if you have any other issues or need more details.

**Comment by EnriqueSolarte** [comment]
Hi @Laplace-Y , 

I was checking the above [error](https://github.com/EnriqueSolarte/ray_casting_mlc/issues/2#issuecomment-2495985773). The modules LGTNet and HorizonNet may not be installed with this package. Can you please run the following commands?: 
```bash
git clone https://github.com/EnriqueSolarte/ray_casting_mlc
cd ray_casting_mlc

# To bring the registered submodules HorizonNet and LGTNet from the original implementations
git submodule update --init --recursive
pip install . 
```
The above lines will clone the repository, and create and set up a directory `build/`.  Finally, this directory is copied into the directory of your Python environment.  Please confirm that your build directory has the following structure.   

> [!Note]
> I fixed some errors in the repository, so you may want to check that you are in the right commit. 

```bash 
.
├── bdist.linux-x86_64
└── lib
    └── ray_casting_mlc
        ├── config
        │   ├── datasets.yaml
        │   ├── general.yaml
        │   ├── path_dirs.yaml
        │   └── trained_models.yaml
        ├── __init__.py
        ├── models
        │   ├── HorizonNet
        │   ├── __init__.py
        │   ├── LGTNet
        │   ├── wrapper_horizon_net
        │   └── wrapper_lgt_net
        ├── ray_tracer
        │   ├── __init__.py
        │   └── ray_tracer.py
        └── utils
            ├── eval_utils.py
            ├── __init__.py
            ├── log_utils.py
            ├── set_random_seed.py
            └── xyz_bev_utils.py
```

**Comment by Laplace-Y** [comment]
Hi, thank you for your previous assistance! I was able to run the earlier parts of the code successfully. However, I'm encountering an issue when running the following command:
```
python experiments/lgt_net/train/train_lgt_net_xyz.py dataset=hm3d_mvl
``` 

The error traceback is as follows:
``` 
(ray-casting-mlc) hlyang@hzh-Precision-7920-Tower:~/ray_casting_mlc_ws/ray_casti                                                                                                                                           ng_mlc$ python experiments/lgt_net/train/train_lgt_net_xyz.py dataset=hm3d_mvl
[2024-11-26 19:23:53,697][root][INFO] - Saved cfg to /home/hlyang/ray_casting_mlc_ws/train_results/train_lgt_net_xyz/lgt_mp3d__hm3d_mvl/241126_192353__0.5_3.0_1__212888/cfg.yaml
[2024-11-26 19:23:53,703][root][INFO] - Seed: 212888
[2024-11-26 19:23:53,787][root][INFO] - MVLDataLoader initialized with:

dataloader: ray_casting_mlc.dataloaders.mvl_dataloader.MVLDataloaderXYZ
dataset_name: hm3d_mvl
img_dir: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/img
labels_dir: /home/hlyang/ray_casting_mlc_ws/pre_computed_data/sampling_ray_casting_pseudo_labels/lgt_mp3d__hm3d_mvl/ray_cast_label
geometry_info_dir: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/geometry_info
scene_list: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/scene_list__training_set.json
size: -1
resolution:
- 512
- 1024
seed: 212888
flip: true
rotate: true
gamma: true
dilation: 4

[2024-11-26 19:23:53,787][root][INFO] - Total data in this dataloader: 24344
[2024-11-26 19:23:53,788][root][INFO] - Seed: 212888
[2024-11-26 19:23:53,797][root][INFO] - MVLDataLoader initialized with:

dataloader: ray_casting_mlc.dataloaders.mvl_dataloader.MVLDataloaderXYZ
dataset_name: hm3d_mvl
img_dir: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/img
labels_dir: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/labels/phi_coords
geometry_info_dir: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/geometry_info
scene_list: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/scene_list__testing_set.json
size: -1
resolution:
- 512
- 1024
seed: 212888
dilation: 4

[2024-11-26 19:23:53,797][root][INFO] - Total data in this dataloader: 2440
[2024-11-26 19:23:53,798][root][INFO] - Loading LGTNet...
/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=ResNet50_Weights.IMAGENET1K_V1. You can also use weights=ResNet50_Weights.DEFAULT to get the most up-to-date weights.
  warnings.warn(msg)
[2024-11-26 19:23:55,930][root][INFO] - LGTNet Wrapper Created
[2024-11-26 19:23:55,931][root][INFO] - Device: cuda:0
[2024-11-26 19:23:55,931][root][INFO] - Loading LGTNet model...
/home/hlyang/ray_casting_mlc_ws/ray_casting_mlc/ray_casting_mlc/models/wrapper_lgt_net/wrapper_lgt_net.py:56: FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt, map_location=torch.device(model.device))
[2024-11-26 19:23:56,378][root][INFO] - ckpt: /home/hlyang/ray_casting_mlc_ws/trained_models/lgt_net/best_mp3d.pkl
[2024-11-26 19:23:56,378][root][INFO] - LGTNet Wrapper Successfully initialized
[2024-11-26 19:23:56,379][root][INFO] - Setting Optimizer: Adam
[2024-11-26 19:23:56,381][root][INFO] - Setting scheduler: ExponentialLR
[2024-11-26 19:23:56,382][root][INFO] - LGTNet ready for training
[2024-11-26 19:23:56,382][root][INFO] - Loss function: weighed_distance_loss
[2024-11-26 19:23:56,382][root][INFO] - Loss function kwargs: {'kappa': 0.5, 'd_min': 3.0, 'gamma': 1}
Testing loop for HorizonNet:   0%|                                                                                                                                                                 | 0/244 [00:00<?, ?it/s]
Error executing job with overrides: ['dataset=hm3d_mvl']
Traceback (most recent call last):
  File "/home/hlyang/ray_casting_mlc_ws/ray_casting_mlc/experiments/lgt_net/train/train_lgt_net_xyz.py", line 52, in main
    pre_trained_eval = lg.test_loop(model, data_loader_test)
  File "/home/hlyang/ray_casting_mlc_ws/ray_casting_mlc/ray_casting_mlc/models/wrapper_lgt_net/wrapper_lgt_net.py", line 186, in test_loop
    dt = next(iterator)
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hlyang/miniconda3/envs/ray-casting-mlc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hlyang/ray_casting_mlc_ws/ray_casting_mlc/ray_casting_mlc/dataloaders/mvl_dataloader.py", line 120, in __getitem__
    label = self.get_label(idx)
  File "/home/hlyang/ray_casting_mlc_ws/ray_casting_mlc/ray_casting_mlc/dataloaders/mvl_dataloader.py", line 113, in get_label
    raise ValueError(f"Label file not found: {label_fn}")
ValueError: Label file not found: /home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/labels/phi_coords/k1cupFYWXJ6_1_room0_84
```
Could you offer any suggestions on how to address this?
Thanks again for your help!

**Comment by EnriqueSolarte** [comment]
Hi @Laplace-Y , 

It seems that the dataloader for testing (initialized in L32 in `experiments/lgt_net/train/train_lgt_net_xyz.py`) -> [here](https://github.com/EnriqueSolarte/ray_casting_mlc/blob/cd375919f5d06627d044c3f7f68fc74c852d8f3a/experiments/lgt_net/train/train_lgt_net_xyz.py#L37), somehow cannot find the label `k1cupFYWXJ6_1_room0_84.npy`. 
Based on your snapshot, this file must exist in the following path:
`/home/hlyang/ray_casting_mlc_ws/mvl_datasets/hm3d_mvl/labels/phi_coords/k1cupFYWXJ6_1_room0_84`.

In your WS `/home/hlyang/ray_casting_mlc_ws/`, you should have something similar to the following structure. 
```
├── mvl_datasets  # downloaded dataset from huggingface 
│   └── hm3d_mvl
│       ├── geometry_info
│       ├── img
│       ├── labels
│       ├── scene_list__testing_set.json
│       └── scene_list__training_set.json
├── pre_computed_data 
│   ├── multi_cycle_ray_casting
│   │   ├── hn_mp3d__hm3d_mvl
│   │   ├── hn_mp3d__mp3d_fpe_mvl
│   │   ├── hn_mp3d__zind_mvl
│   │   ├── lgt_mp3d__hm3d_mvl
│   │   ├── lgt_mp3d__mp3d_fpe_mvl
│   │   └── lgt_mp3d__zind_mvl
│   ├── pre_compute_mlc
│   │   ├── hn_mp3d__hm3d_mvl
│   │   ├── hn_mp3d__mp3d_fpe_mvl
│   │   ├── hn_mp3d__zind_mvl
│   │   ├── lgt_mp3d__hm3d_mvl
│   │   ├── lgt_mp3d__mp3d_fpe_mvl
│   │   └── lgt_mp3d__zind_mvl
│   ├── pre_compute_xyz
│   │   ├── hn_mp3d__hm3d_mvl
│   │   ├── hn_mp3d__mp3d_fpe_mvl
│   │   ├── hn_mp3d__zind_mvl
│   │   ├── lgt_mp3d__hm3d_mvl
│   │   ├── lgt_mp3d__mp3d_fpe_mvl
│   │   └── lgt_mp3d__zind_mvl
│   └── sampling_ray_casting_pseudo_labels
│       ├── hn_mp3d__hm3d_mvl
│       ├── hn_mp3d__mp3d_fpe_mvl
│       ├── hn_mp3d__zind_mvl
│       ├── lgt_mp3d__hm3d_mvl
│       ├── lgt_mp3d__mp3d_fpe_mvl
│       └── lgt_mp3d__zind_mvl
├── ray_casting_mlc
│   ├── assets
│   │   ├── mvl-dataset-light.gif
│   │   └── ray_casting_fig.png
│   ├── build
│   │   ├── bdist.linux-x86_64
│   │   └── lib
│   ├── experiments
│   │   ├── download
│   │   ├── horizon_net
│   │   └── lgt_net
│   ├── ray_casting_mlc
│   │   ├── config
│   │   ├── dataloaders
│   │   ├── __init__.py
│   │   ├── models
│   │   ├── __pycache__
│   │   ├── ray_tracer
│   │   └── utils
│   ├── ray_casting_mlc.code-workspace
│   ├── ray_casting_mlc.egg-info
│   │   ├── dependency_links.txt
│   │   ├── PKG-INFO
│   │   ├── requires.txt
│   │   ├── SOURCES.txt
│   │   └── top_level.txt
│   ├── README.md
│   ├── requirements.txt
│   └── setup.py
├── trained_models
│   ├── horizon_net
│   │   ├── resnet50_rnn__mp3d.pth
│   │   ├── resnet50_rnn__panos2d3d.pth
│   │   ├── resnet50_rnn__st3d.pth
│   │   └── resnet50_rnn__zind.pth
│   └── lgt_net
│       ├── best_mp3d.pkl
│       ├── best_pano2d3d.pkl
│       ├── best_st3d.pkl
│       └── best_zind.pkl
```

Can you do the following, please? 
```
conda activate ${your_conda_env}
cd ${new_WS} #choose a new directory just to be sure
git clone  https://github.com/EnriqueSolarte/ray_casting_mlc.git
cd ray_casting_mlc
pip install -e . 

# download hm3d_mvl and unzip
python experiments/download/mvl_datasets.py 

#download the models 
python experiments/download/pre_trained_models.py

# train the model
python experiments/lgt_net/train/train_lgt_net_xyz.py
```
Please let me know if you find any issues. I am looking forward to your response.

**Comment by Laplace-Y** [comment]
Hi,
Thank you for sharing your project. I carefully followed the steps you provided:

```
conda activate ${your_conda_env}
cd ${new_WS} #choose a new directory just to be sure
git clone  https://github.com/EnriqueSolarte/ray_casting_mlc.git
cd ray_casting_mlc
pip install -e . 

# download hm3d_mvl and unzip
python experiments/download/mvl_datasets.py 

#download the models 
python experiments/download/pre_trained_models.py

# train the model
python experiments/lgt_net/train/train_lgt_net_xyz.py
``` 

However, I encountered the same error during execution. I’ve verified each step, but the issue persists. Could you please provide additional guidance or suggestions for troubleshooting? If there are any  specific details you need from my environment to assist, I’d be happy to provide them.

Additionally, I noticed another issue while unzipping the dataset. It seems that there are many duplicate files in the extracted dataset. I am not sure if this is expected or if there might be an issue with the dataset download or extraction process. Could you clarify this or let me know how to resolve it?

Thank you for your time and help!

**Comment by EnriqueSolarte** [comment]
Hi @Laplace-Y, 

Yes, you are right. Some files are duplicated in some zip files, thank you, I did not notice it. However, this is certainly not an issue. Nevertheless, I just added some lines of code [HERE](https://github.com/EnriqueSolarte/ray_casting_mlc/blob/bd54ad24d2f09884b5c60683e8879d834bb48887/experiments/download/mvl_datasets.py#L38-L57) to handle this. 

By now, you may have noticed that we used OmegaConfig and Hydra to handle our parameter configurations. The rule of thumb is as follows: every script mostly has a `cfg.ymal` in the same directory. This configuration file holds all configurations for that script, including the directories, loading dataset, and predefined settings. 

When you run `python experiments/download/mvl_datasets.py` you are automatically loading  `experiments/download/cfg.yaml` into the instance object `cfg` [HERE](https://github.com/EnriqueSolarte/ray_casting_mlc/blob/bd54ad24d2f09884b5c60683e8879d834bb48887/experiments/download/mvl_datasets.py#L60-L64). Note that this object is passed to the whole system. This explanation also applies when running `experiments/lgt_net/train/train_lgt_net_xyz.py`. 

Could you confirm the following:
1. Your workspace directory is `/home/hlyang/ray_casting_mlc_ws/`. Can I see it?
```
cd ${WS}
#to draw a tree hierarchy for the dirrectory
tree -L 4 .
```
3. The dataset you downloaded is at `/home/hlyang/ray_casting_mlc_ws/mvl_datasets/ `, I am right?
4. In `/home/hlyang/ray_casting_mlc_ws/mvl_datasets/`, you should see a structure as follows. 
```
.
├── hm3d_mvl
│   ├── geometry_info
│   ├── img
│   ├── labels
│   ├── scene_list__testing_set.json
│   └── scene_list__training_set.json
└── mp3d_fpe_mvl
    ├── geometry_info
    ├── img
    ├── labels
    ├── scene_list__testing_set.json
    └── scene_list__training_set.json
```
5. Could you share the commit you are working on?
```
git log 
```
I am looking forward to your response.
